# Generated by Django 5.2.12 on 2026-03-16 10:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField(default='')),
                ('color_start', models.CharField(default='#6c757d', max_length=7)),
                ('color_end', models.CharField(default='#495057', max_length=7)),
                ('icon', models.CharField(default='🎬', max_length=10)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('year', models.IntegerField()),
                ('rating', models.FloatField()),
                ('description', models.TextField()),
                ('director', models.CharField(max_length=100)),
                ('cast', models.CharField(max_length=500)),
                ('duration', models.IntegerField(help_text='Duration in minutes')),
                ('poster_color_start', models.CharField(default='#1a1a2e', max_length=7)),
                ('poster_color_end', models.CharField(default='#16213e', max_length=7)),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movies', to='movies.genre')),
            ],
            options={
                'ordering': ['-rating', 'title'],
            },
        ),
    ]
